### PR TITLE
Always Bet on HTML (blog post)

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
N / A

## Summary of Changes
1. Created top level Blog page route and updated navigation
1. Presenting a first draft for a blog post hoping to capture and convey the spirit and motivations of Project Evergreen and its projects (and maintainers)

_Looking for any and all feedback on the substance and tone of the content and of course I'm sure there are still a number of spelling mistakes._  🙃 

## TODO
1. [x] Left some placeholder CSS, but the blog posts will definitely need some styling help before merging
1. [x] Feels a bit verbose, would like to try and condense more of the content into fewer words, but maybe styling could also help things breath a bit more as well?
1. [x] More proof-reading, [spell checking](https://github.com/ProjectEvergreen/greenwood/discussions/638), etc
1. [ ] Would like to find some more images or otherwise try and break up the current feeling of a wall of text in places (or just edit more 😅  )
    - https://www.reddit.com/r/webdev/comments/ogrt5u/100_illustration_resources_for_your_new/
    - https://www.drawkit.io/product/working-from-home-illustrations
    - 
1. [x] Deploy preview looks pretty bad on mobile 🥺

### CODE REVIEW

**Comment by aholtzman** [comment]
@thescientist13 I pushed some styling and spelling fixes. Overall I think it is a good post, you should have someone who is adept at copy editing help with the next draft (that is not in  my skillsets).

**Comment by thescientist13** [comment]
Thanks so much for providing a little TLC on this @aholtzman and appreciate the positive sentiment towards the post in general! 🙏 

> you should have someone who is adept at copy editing help with the next draft 

Yeah, for sure.  I'll be doing a little general outreach over the next couple days for myself and Project Evergreen and will see if anyone is willing to help out on content creation and curation (and would also be super helpful for website / marketing type content as well, like for greenwoodjs.io).  

Otherwise, I'll definitely be taking another look over the whole thing in a couple days after having had a chance to step back and see if I can tighten things up some more.

Thanks again for your help!  💚

**Comment by thescientist13** [comment]
@aholtzman 
Looks prefect now!  🤗 🏆 
IMG_7928

(though the heading alignment is _slightly_ off on just a blog post page, but I'm sure I can figure that one out)

**Comment by thescientist13** [comment]
got it 💥

**Comment by thescientist13** [comment]
Ok, thanks to some of the early styling and content editing help from @aholtzman , gonna formally move this into ready for review.  Going to do one more pass myself and maybe look for some more images, but otherwise if this were to get merged, I would be pretty happy with it.

**Pull request merged**
