### PR TITLE
fix header size in Safari browser, issue with flexbox

### PR DESCRIPTION
**Pull request by aholtzman**
I noticed an issue with the header rendering oddly in Safari, was a flex box issue

### CODE REVIEW

**Comment by thescientist13** [comment]
Nice, thanks for this!  What was the issue you saw?  Do you have a screenshot by chance?

**Comment by aholtzman** [comment]
Screen Shot 2020-10-03 at 6 01 51 PM

**Comment by thescientist13** [comment]
Ah, yeah.  that's pretty borked.  😆

**Review by thescientist13 — APPROVED** [review]
Looks good on Safari to me!

**Pull request merged**
